package com.zafra.starterapp.models;

import lombok.Data;

//CENSUS YEAR|TRACT|BLOCK GROUP|FIPS ID|TOTAL POPULATION|POPULATION WHITE|POPULATION BLACK|POPULATION ASIAN|POPULATION OTHER|POPULATION AMERICAN INDIAN|POPULATION PACIFIC ISLANDER
// |POPULATION ONE RACE|POPULATION MULTI RACE|POPULATION 25 OLDER|MEDIAN AGE|MEDIAN HOUSEHOLD INCOME|HIGH SCHOOL MALE|HIGH SCHOOL MORE MALE|COLLEGE 1 YR LESS MALE|COLLEGE 1 YR MORE MALE|ASSOCIATES DEGREE MALE|BACHELORS DEGREE MALE|MASTERS DEGREE MALE|PROFESSIONAL DEGREE MALE|DOCTORAL DEGREE MALE|HIGH SCHOOL FEMALE|HIGH SCHOOL MORE FEMALE|COLLEGE 1 YR LESS FEMALE|COLLEGE 1 YR MORE FEMALE|ASSOCIATES DEGREE FEMALE|BACHELORS DEGREE FEMALE|MASTERS DEGREE FEMALE|PROFESSIONAL DEGREE FEMALE|DOCTORAL DEGREE FEMALE|PERCENT 25 YR OVER HIGH SCHOOL MORE|HOUSING UNITS|OCCUPIED HOUSING UNITS|OWNER OCCUPIED HOUSING|RENTER OCCUPIED HOUSING|PERCENT OWNER OCCUPIED|PERCENT RENTER OCCUPIED|MEDIAN HOUSE VALUE OWNER OCCUPIED|MEDIAN YEAR BUILT|VACANCY RATES
//    2010|1 |1|220330001001|1624|73|1529|3|3|0|0|1608|16|893|28.4|28300|170|101|10|44|7|40|0|0|0|107|324|22|171|78|37|16|0|0|43.38%|585|498|669|1111|37.58%|62.42%|$67800.00|1969|14.87%
@Data
public class Statistics {
  private Integer censusYear;
  private Integer tract;
  private Integer blockGroup;
  private Integer fipsId;
  private Integer totalPopulation;
  private Integer populationWhite;
  private Integer populationBlack;
  private Integer populationAsian;
  private Integer populationOther;
  private Integer populationAmericanIndian;
  private Integer populationPacificIslander;
  private Integer populationOneRace;
  private Integer ignore;
}
